### ISSUE TITLE
Crash when drag and dropping a subgroup to an empty slot.

### ISSUE THREAD

**Issue by stormcone** [J0anJosep/OpenTTD#3]
## Version of OpenTTD
JJ-v018

## Expected result
Nothing happens

## Actual result
The games crashes

## Steps to reproduce
- One of the vehicle list windows create 2 groups
- Make one of them the subgroup of the other
- Drag and drop the subgroup into an empty slot in the list

**Comment by J0anJosep** [comment]
Sorry!
I didn't see it or I forgot to answer in its time.
I was busy at the time. Now I have little time to code in OpenTTD and as that branch is really old, I will drop out most of the group changes.

**Comment by J0anJosep** [comment]
I will check it if I ever rebase the old branch. Right now, I will concentrate on other features.
