### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by yozora3** [J0anJosep/OpenTTD#8]
### Expected result

Plane should land without making a loop

### Actual result

Plane makes a loop before landing

### Steps to reproduce

1. Load the savegame. 2. Follow the plane and observe
[bug.zip](https://github.com/user-attachments/files/16335878/bug.zip)

**Comment by J0anJosep** [comment]
Thanks for reporting it. It will be fixed in the next version.

The crash you commented on Discord about modifying a reserved path should happen. How did you manage to do it?

**Comment by J0anJosep** [comment]
Thanks for reporting it. It will be fixed in the next version.

The crash you commented on Discord about modifying a reserved path should *NOT* happen. How did you manage to do it?

**Comment by J0anJosep** [comment]
If you still can crash the game removing tracks, let me know.
